name: fumo_cord
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.17.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  utf_convert: ^0.10.0+1
  http: ^0.13.3


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
